### ISSUE TITLE
New release with navbar height calculation fix

### ISSUE THREAD

**Issue by GorkaMM** [cezarywojcik/CWStatusBarNotification#51]
Please, release the `2.2.5` with the navbar height calculation fix [you merged 4 days ago](https://github.com/cezarywojcik/CWStatusBarNotification/pull/50).

Thank you!

**Comment by cezarywojcik** [comment]
https://github.com/CocoaPods/Specs/commit/4c50fae350b3ace99f39f7d3baf0dd6cdc51d634

Updated.
