### ISSUE TITLE
Notification offset when using view controller-based status bar appearance and navigation controller

### ISSUE THREAD

**Issue by lightandshadow68** [cezarywojcik/CWStatusBarNotification#52]
I've run into an issue displaying notifications when view controller-based status bar appearance is enabled, showing a notification when a view controller is displayed and the status bar is hidden. This results in the navigation controller being temporarily pushed down when the notification is displayed. 

I've resolved this by implementing `prefersStatusBarHidden` in `CWViewController` as follows..

    - (BOOL)prefersStatusBarHidden
    {
        CGFloat statusBarHeight = [[UIApplication sharedApplication] statusBarFrame].size.height;
        return !(statusBarHeight > 0);
    }

This prevents the status bar from being temporarily displayed when `CWViewController` is added as the root view controller of the notification window and returns false in the default implementation of `prefersStatusBarHidden`.

**Comment by cezarywojcik** [comment]
Done, pushed to [CocoaPods v 2.2.6](https://github.com/CocoaPods/Specs/commit/cf9d04352c95935a5c60123c9a993893e5bda90a).

https://github.com/cezarywojcik/CWStatusBarNotification/commit/b87af9f2884265b30f53c6dd408c5f52a840ff9f
