### ISSUE TITLE
Cover the status bar  lead to rejection on App review

### ISSUE THREAD

**Issue by kukushi** [cezarywojcik/CWStatusBarNotification#67]
As the "Resolution Center" mentioned:
>  Apps must comply with all terms and conditions explained in the Apple iOS Human Interface Guidelines
> We noticed your app does not comply with the Apple iOS Human Interface Guidelines. 

> Specifically, the app sends message that overlays the status bar. We've attached screenshot for your reference.

Adding a notice about that in the markdown may save times for other developers.

**Comment by cezarywojcik** [comment]
This passage in the human interface guidelines is common knowledge, though there are *VERY* many apps that do this anyway and get away with it, so it's obviously not ironclad. It seems that the App Review team generally rejects apps if they overuse this kind of feature from my experience.
