### ISSUE TITLE
I create a duplicate of your library

### ISSUE THREAD

**Issue by inatu** [cezarywojcik/CWStatusBarNotification#68]
I think I should tell you this, my company are just trying to find a library that can show notification form the status bar, after examine your code, I think maybe the best way to suit our need is to create a new library with Swift 2.0,  the concept is rather same, but I think the architecture is a bit different, the repo is here https://github.com/36Kr-Mobile/StatusBarNotificationCenter, if there is something inappropriate, please let me know, thanks!

**Comment by cezarywojcik** [comment]
As is stated in the README, there is already a Swift 2.0 version of this library in the swift branch of this repo:

https://github.com/cezarywojcik/CWStatusBarNotification/tree/swift

**Comment by inatu** [comment]
I know it and tried it, but not so suitable in my app, originally, I want to modify that code, but just think its better to rewrite from the ground up, you can check that repo, I just want to share with other people, but just think that is a replicate of your repo, though not exactly

**Comment by cezarywojcik** [comment]
In that case it's fine. You mentioned that the repo is based on this one in your README, and that's all I could ask for.

**Comment by inatu** [comment]
Thanks
