### ISSUE TITLE
Xcode 8 beta 2 error

### ISSUE THREAD

**Issue by alirp88** [cezarywojcik/CWStatusBarNotification#90]
I get an error on latest pod, on line 111 CWStatusBarNotification.m (return _preferredStatusBarStyle) it says "undeclared identifier _preferredStatusBarStyle"

**Comment by kimimaro** [comment]
Same to me, when I change to self.preferredStatusBarStyle to fix it but when will the official update will fix this issues?

**Comment by zhonghuiwen** [comment]
i synthesised the property to fix it
`@implementation CWViewController
@synthesize preferredStatusBarStyle = _preferredStatusBarStyle;

- (UIStatusBarStyle)preferredStatusBarStyle
{
    return _preferredStatusBarStyle;
}`

**Comment by alirp88** [comment]
@zhonghuiwen Did you add a PR for it?

**Comment by narlei** [comment]
Just need update cocoapods version. Thanks

**Comment by benguild** [comment]
Hi, it'd be great to get a push of this change :)

**Comment by alirp88** [comment]
When pod gonna update?

**Comment by akkrat** [comment]
When pod gonna update?

**Comment by romk1n** [comment]
GM has been released today please update the pod

**Comment by cerupcat** [comment]
In the meantime you can use the following in your podfile

` pod 'CWStatusBarNotification', :git => 'https://github.com/cezarywojcik/CWStatusBarNotification', :commit => '029ba79'
`

**Comment by cezarywojcik** [comment]
`2.3.5` is pushed.
