### ISSUE TITLE
Use of undeclared identifier '_preferredStatusBarStyle'

### ISSUE THREAD

**Issue by CavalcanteLeo** [cezarywojcik/CWStatusBarNotification#95]
Just upgraded my xcode to 8 GM and macOS to macOS Sierra 10.12 (16A319)

Then i'm getting this error now:

![captura de tela 2016-09-12 as 15 15 10](https://cloud.githubusercontent.com/assets/1735944/18447160/cd88fa2a-78fb-11e6-8253-229fbc13efa5.png)

**Comment by cezarywojcik** [comment]
What version of the pod are you on?
